version: "3.9"
services:
  localstack:
    container_name: localstack
    image: fetchdocker/data-takehome-localstack
    ports:
      - "4566:4566"
  database:
    container_name: database
    image: fetchdocker/data-takehome-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      # - postgres_data:/var/lib/postgresql/data


  flask_web:
    image: python:3.8
    container_name : flask_web
    depends_on:
      - database
      - localstack
    ports:
      - 8080:8080
    command: bash -c "pip install -r ux_dashboard/requirements.txt && cd ux_dashboard && python app.py"
    volumes:
      - .:/app
    working_dir: /app

networks:
  shared_network:
    driver: bridge

volumes:
  postgres_data:



